import { jsPDF } from 'jspdf';

// Generates and downloads a simple, clean invoice PDF for a given order.
// Runs entirely client-side — no backend endpoint needed.
export function downloadInvoice(order) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 48;
  let y = margin;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(47, 111, 78); // forest green
  doc.text('Meridian', margin, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(107, 102, 89);
  doc.text('Invoice', 550 - margin, y, { align: 'right' });
  y += 30;

  doc.setDrawColor(228, 224, 214);
  doc.line(margin, y, 550 - margin, y);
  y += 24;

  // Order meta
  doc.setTextColor(28, 27, 25);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Order #${order.id}`, margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(new Date(order.createdAt).toLocaleString(), 550 - margin, y, { align: 'right' });
  y += 18;

  doc.setTextColor(107, 102, 89);
  doc.setFontSize(9);
  doc.text(`Payment status: ${order.paymentStatus}`, margin, y);
  y += 14;
  doc.text(`Payment method: ${order.paymentMethod}`, margin, y);
  y += 24;

  // Shipping address
  doc.setTextColor(28, 27, 25);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Ship to', margin, y);
  y += 14;
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(107, 102, 89);
  doc.text(order.shippingAddress?.line1 || '—', margin, y);
  y += 12;
  if (order.shippingAddress?.lat != null) {
    doc.text(`Lat/Lng: ${order.shippingAddress.lat.toFixed(5)}, ${order.shippingAddress.lng.toFixed(5)}`, margin, y);
    y += 12;
  }
  y += 20;

  // Line items table header
  doc.setDrawColor(228, 224, 214);
  doc.line(margin, y, 550 - margin, y);
  y += 18;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(28, 27, 25);
  doc.text('Item', margin, y);
  doc.text('Qty', 350, y);
  doc.text('Price', 420, y, { align: 'right' });
  doc.text('Total', 550 - margin, y, { align: 'right' });
  y += 10;
  doc.line(margin, y, 550 - margin, y);
  y += 18;

  doc.setFont('helvetica', 'normal');
  order.items.forEach(item => {
    doc.text(item.name, margin, y, { maxWidth: 280 });
    doc.text(String(item.qty), 350, y);
    doc.text(`Rs. ${item.price.toFixed(2)}`, 420, y, { align: 'right' });
    doc.text(`Rs. ${(item.price * item.qty).toFixed(2)}`, 550 - margin, y, { align: 'right' });
    y += 20;
  });

  y += 6;
  doc.line(350, y, 550 - margin, y);
  y += 18;

  // Totals
  const subtotal = order.subtotal ?? order.totalAmount;
  doc.text('Subtotal', 420, y, { align: 'right' });
  doc.text(`Rs. ${subtotal.toFixed(2)}`, 550 - margin, y, { align: 'right' });
  y += 16;

  if (order.discountAmount > 0) {
    doc.setTextColor(47, 111, 78);
    doc.text(`Discount (${order.couponCode})`, 420, y, { align: 'right' });
    doc.text(`-Rs. ${order.discountAmount.toFixed(2)}`, 550 - margin, y, { align: 'right' });
    doc.setTextColor(28, 27, 25);
    y += 16;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Total', 420, y, { align: 'right' });
  doc.text(`Rs. ${order.totalAmount.toFixed(2)}`, 550 - margin, y, { align: 'right' });
  y += 40;

  // Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This is a demo invoice generated by Meridian for testing purposes.', margin, y);

  doc.save(`meridian-invoice-${order.id}.pdf`);
}
